### ISSUE TITLE
Node documentation

### ISSUE THREAD

**Issue by GregTheGreek** [ConnextProject/docs#5]
It seems the node documentation is lacking documentation, any plans for including that information?

**Comment by ArjunBhuptani** [comment]
Oops! We haven't been keeping track of issues in this repo.

Docs for spinning up and using the node are available in the indra monorepo readme - https://github.com/ConnextProject/indra.

Consolidating these with our client docs is still a TODO on our end. Hope that helps (in case you were still looking)!
